name: Delete Workflow Runs

on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * *"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 15
